flaskr/controllers/window.py
import functools
from os import name
from signal import raise_signal

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for, abort, jsonify
)
from flaskr.storage.window_data import WindowData
window = WindowData()

from flaskr.controllers import auth

bp = Blueprint('window', __name__)
bp_api = Blueprint('api-window', __name__, url_prefix='/api/window')

@bp.route('/')
@auth.login_required
def index():
    return render_template('window/index.html', window=window.get_dict())

@bp_api.route('/', methods=['GET'])
@auth.login_required
def api_window():
    return jsonify(window.get_dict())


@bp.route('/window/update', methods=('GET', 'POST'))
@auth.login_required
def update():
    if request.method == 'POST':
        error = None

        name = request.form['name']
        if not name:
            error = 'Title is required.'

        openDirection = request.form['opendirection']

        openAngle = request.form['openangle']

        if error is not None:
            flash(error)
        else:
            window.update_window_data(name, openDirection, openAngle)
            
            return redirect(url_for('window.index'))

    return render_template('window/update.html')

@bp_api.route('/update', methods=( 'PUT', ))
@auth.login_required
def api_update():

    try:
        name = request.json['name']
    except:
        return jsonify({'error': 'name is missing...'}), 400
    try:
        openDirection = request.json['openDirection']
        if openDirection != 'left' and openDirection != 'right':
            raise ValueError
    except ValueError:
        return jsonify({'error': 'openDirection must be left or right...'}), 400
    except:
        return jsonify({'error': 'openDirection is missing...'}), 400
    try:
        openAngle = request.json['openAngle']
        if type(openAngle) != float or openAngle < 0 or openAngle > 90:
            raise ValueError
    except ValueError:
        return jsonify({'error': 'openAngle should be a float between 0 and 90...'}), 400 
    except:
        return jsonify({'error': 'openAngle is missing...'}), 400

    window.update_window_data(name, openDirection, openAngle)
        
    return jsonify({'message': 'Window data has been updated with success!'}), 200

flaskr/templates/window/create.html
{% extends 'base.html' %} {% block header %}
<h1>{% block title %}Configurate Window{% endblock %}</h1>
{% endblock %} {% block content %}
<form method="post">
  <label for="name">Name</label>
  <input name="name" id="name" value="{{ request.form['name'] }}" required />

  <label for="opendirection">Open direction </label>
  <select name="opendirection" id="opendirection">
    <option value="left">Left</option>
    <option value="fold">Fold</option>
    <option value="right">Right</option>
  </select>

  <label for="openangle">Open angle </label>
  <input
    type="number"
    min="0"
    max="90"
    name="openangle"
    step="5"
    id="openangle"
    value="{{ request.form['openangle'] }}"
    required
  />

  <label for="integrity">Integrity </label>
  <input
    type="number"
    name="integrity"
    min="0"
    max="100"
    step="1"
    id="integrity"
    value="{{ request.form['integrity'] }}"
  />

  <input type="submit" value="Save" />
</form>
{% endblock %}

flaskr/templates/window/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Window{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('window.update') }}">Update</a>
  {% endif %}
{% endblock %}

{% block content %}
 
    <article class="post">
    
        <h1>Name:{{window["name"] }}</h1>
        <hr>
        <p>Open Direction: {{ window["openDirection"] }}</p> 
        <hr>
        <p>Open Angle: {{ window["openAngle"] }}</p>
        <hr>
        <p>Integrity: {{ window["integrity"] }}</p>
        <hr>
     
    </article>
    
  
{% endblock %}

flaskr/templates/window/update.html
{% extends 'base.html' %} {% block header %}
<h1>{% block title %}Configurate Window{% endblock %}</h1>
{% endblock %} {% block content %}
<form method="post">
  <label for="name">Name</label>
  <input name="name" id="name" value="{{ request.form['name'] }}" required />

  <label for="opendirection">Open direction </label>
  <select name="opendirection" id="opendirection">
    <option value="left">Left</option>
    <option value="fold">Fold</option>
    <option value="right">Right</option>
  </select>

  <label for="openangle">Open angle </label>
  <input
    type="number"
    min="0"
    max="90"
    name="openangle"
    id="openangle"
    value="{{ request.form['openangle'] }}"
    required
  />

  <input type="submit" value="Save" />
</form>
{% endblock %}